# Generated by Django 5.2 on 2025-04-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchlsit',
            new_name='watchlist',
        ),
    ]
