# Generated by Django 5.2 on 2025-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
